### ISSUE TITLE
Vote on the frontend framework that we are going to use

### ISSUE THREAD

**Issue by papac** [liberty-space/liberty-ui#1]
❤️ For ReactJs
😄 For Angular
🎉 For VueJs
👍 For JavaScript Vanilla

**Comment by arnoldkouya** [comment]
Hi all,
My choice is 😄 Angular 

Best Regards

**Comment by daohassane** [comment]
Hi there,
🎉

**Comment by houssenedao** [comment]
![image](https://user-images.githubusercontent.com/16049399/104290970-e3576700-54b2-11eb-97a2-f94a1c926533.png)

**Comment by papac** [comment]
:heart:

**Comment by daohassane** [comment]
you will have to impose a tool.

**Comment by papac** [comment]
Here we have to 🎉 .
So we are going to use VueJs
@daohassane  can you init the repo

**Comment by daohassane** [comment]
Of course
